version: '3.8'

services:
  anime-saas-front:
    build:
      context: ./anime-saas-front
      dockerfile: Dockerfile.dev
    container_name: anime-saas-front
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./anime-saas-front:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3

  anime-saas-api:
    build:
      context: ./anime-saas-api
    container_name: anime-saas-api
    command: dotnet watch run --urls=http://0.0.0.0:8080
    volumes:
      - ./anime-saas-api/AnimeSaasApi:/src
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=anime-saas-mysql;Port=3306;Database=anime_saas_db;User=${API_USER};Password=${API_USER_PASSWORD}
    depends_on:
      - anime-saas-mysql

  anime-saas-mlservice:
    build:
      context: ./anime-saas-mlservice
    container_name: anime-saas-mlservice
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - ./anime-saas-mlservice/app:/app
    ports:
      - "5000:5000"
    depends_on:
      - anime-saas-mysql

  anime-saas-mysql:
    image: mysql:8
    container_name: anime-saas-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: anime_saas_db
      MYSQL_USER: animeuser
      MYSQL_PASSWORD: animepass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: