FROM mcr.microsoft.com/dotnet/sdk:8.0 AS test-env

WORKDIR /app
COPY . .

# Restore la solution principale ou le projet test
RUN dotnet restore ./anime-saas-api/anime-saas-api.sln

# Build
RUN dotnet build ./anime-saas-api/anime-saas-api.sln --no-restore

# Lancer les tests du projet test
RUN dotnet test ./tests/anime-saas-api.Tests/anime-saas-api.Tests.csproj --no-build --verbosity normal